linters:
  enable:
    - depguard
    - dupl
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - thelper
    - unused
    - usestdlibvars

linters-settings:
  depguard:
    rules:
      Main:
        deny:
          - pkg: github.com/hashicorp/go-multierror
            desc: "use errors instead"
          - pkg: github.com/pkg/errors
            desc: "use errors instead"
  dupl:
    threshold: 400
  gomodguard:
    blocked:
      modules:
        - github.com/evanphx/json-patch:
            recommendations:
              - github.com/evanphx/json-patch/v5

issues:
  exclude-use-default: false
run:
  timeout: 10m